<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/admin/admin.css">

<main class="container">
  <h2>Récapitulatif des commandes</h2>

  <a class="back" href="<?= $requestUrl ?>/users/admin"><i class="fas fa-arrow-circle-left"></i> Retour vers l'admin</a>
  <p>Cliquez sur un numéro de commande pour voir le détail !</p>
  <table class="t-order">
    <thead>
      <tr><th>Numéro de commande</th>
        <th>Prix total</th>
        <th>Date de la commande</th>
      </tr></thead>
      <tbody>
        <?php foreach ($orders as $order): ?>
          <tr>
            <td class='link'><a href="<?= $requestUrl ?>/users/admin/order/orderdetail?id=<?=$order['Id']?>"><?=$order['Id']?></a></td>
            <td><?=$order['TotalAmount']?> €</td>
            <td><?=date('d/m/Y', strtotime($order['CreationTimestamp']))?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </main>
