<script  src="https://code.jquery.com/jquery-3.1.1.min.js"  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="  crossorigin="anonymous"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" ></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="<?= $wwwUrl ?>/css/users/user.css">

<?php if ($error != null) { ?>
  <small style="color: red; margin-left:370px; font-style: italic;"><?= $error ?></small>
<?php } ?>
<main class="container">

  <div class="veen">
    <div class="login-btn splits">
      <p>Déjà un compte ?</p>
      <button class="active">Connectez vous !</button>
    </div>
    <div class="rgstr-btn splits">
      <p>Pas encore de compte ?</p>
      <button>Enregistrez vous !</button>
    </div>
    <div class="wrapper">
      <form id="login" action="<?= $requestUrl ?>/users/login" method="POST">
        <h3>Connectez vous !</h3>
        <div class="mail">
          <input type="text" name="email">
          <label>Email ou Pseudo</label>
        </div>
        <div class="passwd">
          <input type="password" name="password">
          <label>Password</label>
        </div>
        <div class="submit">
          <button class="dark">Connexion</button>
        </div>
      </form>
      <form id="register" action="<?= $requestUrl ?>/users/register" method="POST">
        <h3>Enregistrez vous !</h3>
        <div class="name">
          <input type="text" name="firstname">
          <label>Prénom</label>
        </div>
        <div class="name">
          <input type="text" name="lastname">
          <label>Nom</label>
        </div>
        <div class="mail">
          <input type="mail" name="email">
          <label>Email</label>
        </div>
        <div class="uid">
          <input type="text" name="pseudo">
          <label>Pseudo</label>
        </div>
        <div class="uid">
          <input type="text" name="address">
          <label>Votre adresse</label>
        </div>
        <div class="uid">
          <input type="text" name="city">
          <label>Ville</label>
        </div>
        <div class="uid">
          <input type="text" name="zip">
          <label>Code postal</label>
        </div>
        <div class="passwd">
          <input type="password" name="password">
          <label>Mot de passe</label>
        </div>
        <div class="submit">
          <button class="dark">C'est parti !</button>
        </div>
      </form>
    </div>
  </div>
</main>
<script type="text/javascript" src='<?= $wwwUrl ?>/js/user.js'></script>
