<link rel="stylesheet" href="<?= $wwwUrl ?>/css/basket/basket.css">
<link rel="stylesheet" type="text/css" href="<?= $wwwUrl ?>/css/payment/payment.css">
<main class="container">
  <h3>Votre paiement a été accepté !</h3>
  <p>Félicitation votre commande <span>n° <?= $user ?> </span>a été enregistrée !</p>
  <a class="back" href="<?= $requestUrl ?>"><i class="fas fa-arrow-circle-left"></i> Retour vers l'accueil</a>
  <img src="https://media0.giphy.com/media/AhhGtrpj5ZxGZER5yC/giphy.gif?cid=790b7611171c0f557ebe1b6886cb211614ef548afcf4a383&rid=giphy.gif" alt="sucess gif">
</main>
